### PR TITLE
Depend on malcontent-data instead of eos-parental-controls-data

### PR DESCRIPTION
**Pull request by andrunko**
https://phabricator.endlessm.com/T26537

### CODE REVIEW

**Comment by andrunko** [comment]
Tested locally and it seems to work fine.

**Comment by uajain** [comment]
Q: Do we also need to remove the generation of `eos-parental-controls-data` from `debian/control` ?

**Comment by uajain** [comment]
I can confirm that it also worked in my local testing. I tested my [gnome-control-center PR](https://github.com/endlessm/gnome-control-center/pull/176) with this eos-parental-control branch changes. I was able to install `malcontent-data` (and eventually `libmalcontent-0-dev` which is the dep for my gnome-control-center PR).

**Comment by pwithnall** [comment]
> Q: Do we also need to remove the generation of `eos-parental-controls-data` from `debian/control` ?

Shouldn’t need to. It’s fine for that package to be built by OBS and then not pulled into image builds.

**Review by pwithnall — APPROVED** [review]

**Pull request merged**
